Rails.application.routes.draw do
  root "home#index"
  # Authentication (generated by: rails generate authentication)
  resource :session
  resources :users, only: [:create]
  resources :passwords, param: :token

  post "locale", to: "locales#update", as: :update_locale

  # Health check for load balancers + Kamal
  get "up" => "rails/health#show", as: :rails_health_check

  # PWA manifest + service worker (Rails 8 native)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Sidekiq web UI (production: mount behind authentication)
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq" if Rails.env.development?

  # Game routes
  resources :planets
end
