Rails.application.routes.draw do
  match "/400", to: "errors#bad_request",           via: :all
  match "/404", to: "errors#not_found",             via: :all
  match "/422", to: "errors#unprocessable_entity",  via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  root "home#index"
  # Authentication (generated by: rails generate authentication)
  resource :session
  resources :users, only: [:create]
  resources :passwords, param: :token

  post "locale", to: "locales#update", as: :update_locale

  # Health check for load balancers + Kamal
  get "up" => "rails/health#show", as: :rails_health_check

  # PWA manifest + service worker (Rails 8 native)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Sidekiq web UI (production: mount behind authentication)
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq" if Rails.env.development?

  # Galaxy map
  get "/galaxy", to: "galaxy#index", as: :galaxy

  # JSON API
  namespace :api do
    resources :planets, only: [:index]
  end

  # Game routes
  resources :planets do
    resources :buildings, only: [:new, :create, :show]
    resource  :construction_queue, only: [:destroy]
    resources :training_queues, only: [:index, :create]
  end

  # Documentation routes
  get "docs",           to: "docs#index",     as: :docs
  get "docs/buildings", to: "docs#buildings", as: :docs_buildings
  get "docs/economy",   to: "docs#economy",   as: :docs_economy
end
